### ISSUE TITLE
Analyse Werk

### ISSUE THREAD

**Issue by Jason2426** [Patrickkhr/connect-your-tribe-squad-page#1]
**Wat is mooi?** 
Het ontwerp is super minimalistisch en vind ik er erg goed uit zien. 

**Wat werkt goed?** 
Je hebt een beetje nagedacht over de functionaliteiten bijvoorbeeld als er op een kaart word geklikt hoe het er dan uit komt te zien en dit ziet er ook netjes en goed uitgedacht uit. 

**Wat werkt niet zo goed** 
De gebruiker zal veel moeten klikken en scrollen misschien is het dus niet de beste manier om het op deze manier te doen want mensen zijn nou eenmaal lui. 

**Wat kan beter?** 
De site is erg minimalistisch wat er super nice uit ziet maar de textvormgeving qua groottes zouden beter weergeven kunnen worden in het ontwerp. Qua functionaliteit zou het ook nog wat beter uitgedacht proberen iets te bedenken waar de gebruiker zo min mogelijk acties hoeft te ondernemen om te krijgen wat die wil

**Comment by Patrickkhr** [comment]
Bedankt voor de tips, ik ga dit meenemen voor de squad page!
