### ISSUE TITLE
Feedback squadpage

### ISSUE THREAD

**Issue by lisavanmansom** [Patrickkhr/connect-your-tribe-squad-page#2]
**Wat is mooi, wat werkt goed?** 
Nice clean design. Het laat op een duidelijke/dynamische manier de informatie zien van een persoon.

**Wat kan beter? Wat werkt niet zo goed?**
Misschien is het leuk om het design unieker te maken, door bijvoorbeeld meer kleurgebruik of elementen toe te voegen.

**Comment by Patrickkhr** [comment]
Bedankt voor de suggestie, ik ga meerdere kleuren toepassen zodat het ontwerp er leuker uit gaat zien!
