### ISSUE TITLE
Ontwerp analyseren

### ISSUE THREAD

**Issue by Abeeryu** [Patrickkhr/connect-your-tribe-squad-page#3]
Wat is mooi, Wat werkt goed?

Ik vind het een leuk design, wel duidelijk  voor de endgebruikers.

Wat kan beter, Wat werkt niet goed?
Misschien kan je een beter idee voor een sequad pagina bedenken. Misschien het is niet erg handig om hier scrollen om te gebruiken. Dat kost de gebruiker veel acties om te nemen.

**Comment by Patrickkhr** [comment]
Bedankt voor de tip, ik ga buttons toevoegen zodat de gebruiker hierdoor makkelijker door de kaarten heen kan
